# Scan the Python code for vulnerabilities using Bandit.
name: Bandit

on:
  workflow_call:

env:
  # Set path to the pmreorder tool. At the moment pmreorder is the only
  # Python-based tool released in the PMDK.
  SCAN_DIR: src/tools/pmreorder

jobs:
  bandit:
    name: Bandit
    runs-on: ubuntu-latest
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v3

      - name: Install Bandit
        run: sudo apt-get -y install bandit

      - name: Bandit scan
        run: bandit --version && bandit -r "$SCAN_DIR"
